import { Card, SKIP, WILD } from '@jgames/types'

export const DECK: Card[] = [
  { color: '',       value: SKIP },
  { color: '',       value: SKIP },
  { color: '',       value: SKIP },
  { color: '',       value: SKIP },

  { color: '',       value: WILD },
  { color: '',       value: WILD },
  { color: '',       value: WILD },
  { color: '',       value: WILD },
  { color: '',       value: WILD },
  { color: '',       value: WILD },
  { color: '',       value: WILD },
  { color: '',       value: WILD },

  { color: 'blue',   value: 1 },
  { color: 'blue',   value: 1 },
  { color: 'blue',   value: 2 },
  { color: 'blue',   value: 2 },
  { color: 'blue',   value: 3 },
  { color: 'blue',   value: 3 },
  { color: 'blue',   value: 4 },
  { color: 'blue',   value: 4 },
  { color: 'blue',   value: 5 },
  { color: 'blue',   value: 5 },
  { color: 'blue',   value: 6 },
  { color: 'blue',   value: 6 },
  { color: 'blue',   value: 7 },
  { color: 'blue',   value: 7 },
  { color: 'blue',   value: 8 },
  { color: 'blue',   value: 8 },
  { color: 'blue',   value: 9 },
  { color: 'blue',   value: 9 },
  { color: 'blue',   value: 10 },
  { color: 'blue',   value: 10 },
  { color: 'blue',   value: 11 },
  { color: 'blue',   value: 11 },
  { color: 'blue',   value: 12 },
  { color: 'blue',   value: 12 },

  { color: 'green',  value: 1 },
  { color: 'green',  value: 1 },
  { color: 'green',  value: 2 },
  { color: 'green',  value: 2 },
  { color: 'green',  value: 3 },
  { color: 'green',  value: 3 },
  { color: 'green',  value: 4 },
  { color: 'green',  value: 4 },
  { color: 'green',  value: 5 },
  { color: 'green',  value: 5 },
  { color: 'green',  value: 6 },
  { color: 'green',  value: 6 },
  { color: 'green',  value: 7 },
  { color: 'green',  value: 7 },
  { color: 'green',  value: 8 },
  { color: 'green',  value: 8 },
  { color: 'green',  value: 9 },
  { color: 'green',  value: 9 },
  { color: 'green',  value: 10 },
  { color: 'green',  value: 10 },
  { color: 'green',  value: 11 },
  { color: 'green',  value: 11 },
  { color: 'green',  value: 12 },
  { color: 'green',  value: 12 },

  { color: 'purple', value: 1 },
  { color: 'purple', value: 1 },
  { color: 'purple', value: 2 },
  { color: 'purple', value: 2 },
  { color: 'purple', value: 3 },
  { color: 'purple', value: 3 },
  { color: 'purple', value: 4 },
  { color: 'purple', value: 4 },
  { color: 'purple', value: 5 },
  { color: 'purple', value: 5 },
  { color: 'purple', value: 6 },
  { color: 'purple', value: 6 },
  { color: 'purple', value: 7 },
  { color: 'purple', value: 7 },
  { color: 'purple', value: 8 },
  { color: 'purple', value: 8 },
  { color: 'purple', value: 9 },
  { color: 'purple', value: 9 },
  { color: 'purple', value: 10 },
  { color: 'purple', value: 10 },
  { color: 'purple', value: 11 },
  { color: 'purple', value: 11 },
  { color: 'purple', value: 12 },
  { color: 'purple', value: 12 },

  { color: 'red',    value: 1 },
  { color: 'red',    value: 1 },
  { color: 'red',    value: 2 },
  { color: 'red',    value: 2 },
  { color: 'red',    value: 3 },
  { color: 'red',    value: 3 },
  { color: 'red',    value: 4 },
  { color: 'red',    value: 4 },
  { color: 'red',    value: 5 },
  { color: 'red',    value: 5 },
  { color: 'red',    value: 6 },
  { color: 'red',    value: 6 },
  { color: 'red',    value: 7 },
  { color: 'red',    value: 7 },
  { color: 'red',    value: 8 },
  { color: 'red',    value: 8 },
  { color: 'red',    value: 9 },
  { color: 'red',    value: 9 },
  { color: 'red',    value: 10 },
  { color: 'red',    value: 10 },
  { color: 'red',    value: 11 },
  { color: 'red',    value: 11 },
  { color: 'red',    value: 12 },
  { color: 'red',    value: 12 },
]

/**
 * Shuffles an array in place using the Durstenfeld algorithm
 *
 * @param array - array to shuffle
 */
export function shuffle<T> (array: Array<T>): void {
  for (let i: number = array.length - 1; i > 0; i--) {
    const j: number = Math.floor(Math.random() * (i + 1))
    const temp: T = array[i]
    array[i] = array[j]
    array[j] = temp
  }
}
